services:
  # Open WebUI with Ollama (unlimited tokens)
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
    restart: always
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  # Ollama for local model hosting
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  # Your MCP Server
  mcp-server:
    build: .
    container_name: mcp-server
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
      - ./mcp_server:/app/mcp_server
    environment:
      - MCP_PI_CONFIG=/app/config/hosts.yaml
      - MCP_PI_POLICY=/app/config/policies.yaml
    restart: always
    depends_on:
      - ollama

volumes:
  ollama:
  open-webui:
