# security:
#   api_keys:
#     - "kklWgaHK48zQXttGl35YMQYZMgtntrqJ"
#   jwt_public_key_pem: null  # optionally paste a PEM public key for JWT verification
#   cors_allow_origins:
#     - "http://localhost:3000"
#     - "http://localhost:7800"
#   rate_limit_per_minute: 120

# allowlist:
#   enabled_tools:
#     - ssh_exec
#     - scp_put
#     - scp_get
#     - tmux_ensure
#     - tmux_send_keys
#     - tmux_kill
#     - systemd_service
#     - django_manage
#     - django_runserver_tmux

#   # Only allow safe, expected commands via ssh_exec:
#   ssh_exec_allowed_prefixes:
#     - "echo "
#     - "ls"
#     - "pwd"
#     - "uname"
#     - "df "
#     - "free"
#     - "journalctl "
#     - "git "
#     - "python manage.py "
#     - "pip "
#     - "systemctl "
#     - "tmux "
#     - "ps "
#     - "whoami"
#     - "id"
#     - "cd "      # only works in combination with our exec prefix; keep conservative
#   ssh_exec_denied_substrings:
#     - "rm -rf"
#     - ":(){:|:&};:"  # fork bomb
#     - "mkfs"
#     - "dd if="
#     - ">/dev/sd"
#     - "shutdown"
#     - "reboot"

#   per_target_tools: {}
#     # Optional: restrict tools per host
#     # pi-lan:
#     #   - ssh_exec
#     #   - django_manage
#     #   - django_runserver_tmux


security:
  api_keys:
    - "your-strong-random-api-key"
  cors_allow_origins:
    - "http://localhost:7800"
  rate_limit_per_minute: 120

allowlist:
  enabled_tools:
    - ssh_exec
    - scp_put
    - scp_get
    - tmux_ensure
    - tmux_send_keys
    - tmux_kill
    - systemd_service
    - django_manage
    - django_runserver_tmux
    - git_status
    - git_checkout
    - git_pull
    - deploy_hook

  per_target_tools:
    pi-lan:
      - git_status
      - git_checkout
      - git_pull
      - deploy_hook
      - django_manage
      - systemd_service
      - tmux_ensure
      - tmux_send_keys
      - tmux_kill

  # keep ssh_exec very restricted; you may not need git here anymore
  ssh_exec_allowed_prefixes:
    - "echo "
    - "ls"
    - "pwd"
    - "uname"
    - "df "
    - "free"
    - "journalctl "
    - "systemctl "
    - "tmux "
    - "ps "
    - "whoami"
    - "id"
  ssh_exec_denied_substrings:
    - "rm -rf"
    - ":(){:|:&};:"
    - "mkfs"
    - "dd if="
    - ">/dev/sd"
    - "shutdown"
    - "reboot"