# Copy to hosts.yaml and edit
targets:
  pi-lan:
    host: 10.22.96.113
    port: 22
    username: alok
    private_key_path: C:\Users\alok4\.ssh\id_ed25519
    # Optional: known_hosts_path: /home/youruser/.ssh/known_hosts
    # Optional: connect_timeout: 10
    
    gpio:
      agent_path: "/home/alok/gpio_agent.py"
      default_mode: "BCM"     # or "BOARD"
      allowed_pins:
        BCM: [17, 18, 27, 22, 23, 24, 25]
        BOARD: [11, 12, 13, 15, 16, 18, 22]
      capabilities:
        "17": ["read", "write"]
        "18": ["read", "write", "pwm"]  # PWM-capable pin example
        "27": ["read", "write"]
        "22": ["read", "write"]
        "23": ["read", "write"]
        "24": ["read", "write"]
        "25": ["read", "write"]